lib/biddy_web/router.ex
defmodule BiddyWeb.Router do
  use BiddyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug Biddy.Accounts.GuardianPlugPipeline
  end

  # We use ensure_auth to fail if there is no one logged in
  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", BiddyWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index
    get "/logout", SessionController, :delete

    resources("/users", UserController, only: [:new, :create, :show, :index, :edit, :update])
    resources("/session", SessionController, only: [:create, :new])
    resources "/items", ItemController, only: [:index]
  end

  # Definitely logged in scope
  scope "/", BiddyWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    get "/protected", PageController, :protected
    # resources("/users", UserController, only: [:delete, :edit, :update])
    # resources "/items", ItemController, only: [:new, :create, :edit, :update, :delete, :show]

    resources "/items", ItemController,
      only: [
        :index,
        :show,
        :new,
        :create,
        :edit,
        :update
      ] do
      resources "/bids", BidController, only: [:create]
    end

    resources "/users", UserController, only: [:show, :new, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", BiddyWeb do
  #   pipe_through :api
  # end
end

lib/biddy_web/views/layout_view.ex
defmodule BiddyWeb.LayoutView do
  use BiddyWeb, :view
end

lib/biddy_web/templates/layout/_navbar.html.eex
<nav class="ui stackable menu">
  <div class="ui container">
    <a href="/" class="header item" id="home_tab">
      <img class="logo" src="/images/letter-b.png">
    </a>
    <%= link "Items", to: Routes.item_path(@conn, :index), method: :get, class: "item", id: "items_tab" %>
    <a class="item">Testimonials</a>
    <div class="right menu">
      <%= if Biddy.Accounts.get_current_user(@conn) do %>
        <div class="item">
          <span class="currentUserMessage">Logged in as: <span class="uemail"> <%= Biddy.Accounts.get_current_user(@conn).email %></span></span>
        </div>
        <%= link raw(~s'<i class="sign out alternate icon"></i>Logout'), to: "/logout", class: "item" %>
      <% else %>
        <%= link raw(~s'<i class="sign in alternate icon"></i>Login'), to: Routes.session_path(@conn, :new), class: "item", id: "navbar_login" %>
      <% end %>
    </div>
  </div>
</nav>

lib/biddy_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Biddy</title>
    <!-- Semantic-ui CSS min -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css" integrity="sha256-9mbkOfVho3ZPXfM7W8sV2SndrGDuh7wuyLjtsWeTI1Q=" crossorigin="anonymous" />
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <!-- Jquery min -->
    <script
    src="https://code.jquery.com/jquery-3.1.1.min.js"
    integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
    crossorigin="anonymous"></script>
    <!-- Semantic-ui JS min -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js" integrity="sha256-t8GepnyPmw9t+foMh3mKNvcorqNHamSKtKRxxpUEgFI=" crossorigin="anonymous"></script>
  </head>
  <body>
    <%= render "_navbar.html", conn: @conn %>
    <main role="main" class="ui container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>