lib/biddy_web/router.ex
defmodule BiddyWeb.Router do
  use BiddyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug Biddy.Accounts.GuardianPlugPipeline
  end

  # We use ensure_auth to fail if there is no one logged in
  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", BiddyWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index
    get "/logout", SessionController, :delete

    resources("/users", UserController, only: [:new, :create, :show, :index, :edit, :update])
    resources("/session", SessionController, only: [:create, :new])
    resources "/items", ItemController, only: [:index]
  end

  # Definitely logged in scope
  scope "/", BiddyWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    get "/protected", PageController, :protected
    # resources("/users", UserController, only: [:delete, :edit, :update])
    # resources "/items", ItemController, only: [:new, :create, :edit, :update, :delete, :show]

    resources "/items", ItemController,
      only: [
        :index,
        :show,
        :new,
        :create,
        :edit,
        :update
      ] do
      resources "/bids", BidController, only: [:create]
    end

    resources "/users", UserController, only: [:show, :new, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", BiddyWeb do
  #   pipe_through :api
  # end
end

lib/biddy/auction/item.ex
defmodule Biddy.Auction.Item do
  @moduledoc """
  The Item model
  """
  use Ecto.Schema
  import Ecto.Changeset

  schema "items" do
    field :description, :string
    field :ends_at, :utc_datetime
    field :listed_at, :utc_datetime
    field :title, :string
    ## Associations ##
    has_many :bids, Biddy.Auction.Bid
    belongs_to :user, Biddy.Accounts.User
    timestamps()
  end

  @required_fields ~w(title description)a
  @optional_fields ~w(listed_at ends_at)a

  @doc false
  def changeset(item, attrs) do
    item
    |> cast(attrs, @required_fields ++ @optional_fields)
    |> validate_required(@required_fields)
    |> validate_length(:title, min: 3)
    |> validate_length(:description, max: 200)
    |> validate_change(:ends_at, &validate/2)
  end

  defp validate(:ends_at, ends_at_date) do
    case DateTime.compare(ends_at_date, DateTime.utc_now()) do
      :lt -> [ends_at: "ends_at cannot be in the past"]
      _ -> []
    end
  end
end

lib/biddy_web/controllers/api/item_controller.ex
defmodule BiddyWeb.Api.ItemController do
  use BiddyWeb, :controller
  alias Biddy.Auction

  def index(conn, _params) do
    items = Auction.list_items()
    render(conn, "index.json", items: items)
  end

  def show(conn, %{"id" => id}) do
    item = Auction.get_item_with_bids(id)
    render(conn, "show.json", item: item)
  end
end

lib/biddy_web/controllers/item_controller.ex
defmodule BiddyWeb.ItemController do
  use BiddyWeb, :controller

  alias Biddy.Auction
  alias Biddy.Auction.Item

  def index(conn, _params) do
    items = Auction.list_items()
    render(conn, "index.html", items: items)
  end

  def new(conn, _params) do
    changeset = Auction.change_item(%Item{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"item" => item_params}) do
    user = Guardian.Plug.current_resource(conn)

    case Auction.create_item(user, item_params) do
      {:ok, item} ->
        conn
        |> put_flash(:info, "\"#{item.title}\" was created successfully.")
        |> redirect(to: Routes.item_path(conn, :show, item))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  ###########################################
  def show(conn, %{"id" => id}) do
    item = Auction.get_item_with_bids(id)
    bid = Auction.new_bid()
    render(conn, "show.html", item: item, bid: bid)
  end

  ###########################################

  def edit(conn, %{"id" => id}) do
    item = Auction.get_item!(id)
    changeset = Auction.change_item(item)
    render(conn, "edit.html", item: item, changeset: changeset)
  end

  def update(conn, %{"id" => id, "item" => item_params}) do
    item = Auction.get_item!(id)

    case Auction.update_item(item, item_params) do
      {:ok, item} ->
        conn
        |> put_flash(:info, "Item updated successfully.")
        |> redirect(to: Routes.item_path(conn, :show, item))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", item: item, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    item = Auction.get_item!(id)
    {:ok, _item} = Auction.delete_item(item)

    conn
    |> put_flash(:info, "Item deleted successfully.")
    |> redirect(to: Routes.item_path(conn, :index))
  end
end

lib/biddy_web/views/item_view.ex
defmodule BiddyWeb.ItemView do
  use BiddyWeb, :view
end

lib/biddy_web/templates/item/edit.html.eex
<h1>Edit Item</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.item_path(@conn, :update, @item)) %>

<span><%= link "Back", to: Routes.item_path(@conn, :index) %></span>

lib/biddy_web/templates/item/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
<%= if @changeset.action do %>
  <div class="alert alert-danger">
    <p>Oops, something went wrong! Please check the errors below.</p>
  </div>
<% end %>
<%= label f, :title %>
<%= text_input f, :title %>
<%= error_tag f, :title %>
<%= label f, :description %>
<%= text_input f, :description %>
<%= error_tag f, :description %>
<%= label f, :ends_at %>
<%= datetime_select f, :ends_at %>
<%= error_tag f, :ends_at %>
<div>
  <%= submit "Save" %>
</div>
<% end %>

lib/biddy_web/templates/item/index.html.eex
<h1>Listing Items</h1>
<table class="ui basic table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Listed at</th>
      <th>Ends at</th>
      <th>Highest Bid </th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <%= for item <- @items do %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= format_date(item.inserted_at) %></td>
        <td><%= format_date(item.ends_at) %></td>
        <td><%= if item.bids do %>
            <%= Number.Currency.number_to_currency(get_highest_bid(item.bids).amount) %>
          <% else %>
            0
          <% end %>
        </td>
        <td>
          <%= link "View more", to: Routes.item_path(@conn, :show, item), class: "ui tiny primary button" %>
          <%# <%= link "Edit", to: Routes.item_path(@conn, :edit, item) %>
          <%# <%= link "Delete", to: Routes.item_path(@conn, :delete, item), method: :delete, data: [confirm: "Are you sure?"] %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<span><%= link "New Item", to: Routes.item_path(@conn, :new), class: "ui primary button" %></span>

lib/biddy_web/templates/item/new.html.eex
<h1>New Item</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.item_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.item_path(@conn, :index) %></span>

lib/biddy_web/templates/item/show.html.eex
<h1><%= @item.title %></h1>
<ul>
  <li>
    <strong>Description:</strong>
    <%= @item.description %>
  </li>
  <li>
    <strong>Listed at:</strong>
    <%= format_date(@item.inserted_at) %>
  </li>
  <li>
    <strong>Ends at:</strong>
    <%= format_date(@item.ends_at) %>
  </li>
</ul>
<div style="display: flex; flex-direction: row;">
  <div style="flex: 1">
    <h2>Current bids</h2>
    <div id="bids">
      <%= render_many @item.bids, BiddyWeb.BidView, "bid.html" %>
    </div>
    <%= for bid <- @item.bids do %>
    <% end %>
  </div>
  <div style="flex: 1">
    <%= if Biddy.Accounts.get_current_user(@conn) do %>
      <h2>Place your bid!</h2>
      <%= form_for @bid, Routes.item_bid_path(@conn, :create, @item), [class: "ui form"], fn f -> %>
      <%= if @bid.action do %>
        <div class="alert alert-danger">
          Unfortunately, there are errors in your
          submission. Please correct them below.
        </div>
      <% end %>
      <div class="ui right labeled input">
        <%= label f, :amount, "$", class: "ui label" %>
        <%= error_tag f, :amount %>
        <%= number_input f, :amount, placeholder: "Amount", id: "amount" %>
        <div class="ui basic label">.00</div>
      </div>
      <br />
      <%= submit "Submit", class: "ui primary button"%>
    <% end %>
  <% end %>
</div>
</div>
<div class="ui tiny buttons">
  <%= link "Edit", to: Routes.item_path(@conn, :edit, @item), class: "ui button" %>
  <div class="or"></div>
  <%= link "Back", to: Routes.item_path(@conn, :index), class: "ui positive button" %>
</div>