lib/biddy_web/router.ex
defmodule BiddyWeb.Router do
  use BiddyWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug Biddy.Accounts.GuardianPlugPipeline
  end

  # We use ensure_auth to fail if there is no one logged in
  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", BiddyWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index
    get "/logout", SessionController, :delete

    resources("/users", UserController, only: [:new, :create, :show, :index, :edit, :update])
    resources("/session", SessionController, only: [:create, :new])
    resources "/items", ItemController, only: [:index]
  end

  # Definitely logged in scope
  scope "/", BiddyWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    get "/protected", PageController, :protected
    # resources("/users", UserController, only: [:delete, :edit, :update])
    # resources "/items", ItemController, only: [:new, :create, :edit, :update, :delete, :show]

    resources "/items", ItemController,
      only: [
        :index,
        :show,
        :new,
        :create,
        :edit,
        :update
      ] do
      resources "/bids", BidController, only: [:create]
    end

    resources "/users", UserController, only: [:show, :new, :create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", BiddyWeb do
  #   pipe_through :api
  # end
end

lib/biddy_web/controllers/session_controller.ex
defmodule BiddyWeb.SessionController do
  use BiddyWeb, :controller
  alias Biddy.{Accounts, Accounts.Guardian}

  def new(conn, _) do
    render(conn, "new.html")
  end

  def create(conn, %{"user" => %{"email" => email, "password" => password}}) do
    case Accounts.authenticate_user(email, password) do
      {:ok, user} ->
        conn
        |> Guardian.Plug.sign_in(user)
        |> assign(:user_signed_in?, true)
        # |> configure_session(renew: true)
        |> put_flash(:info, "Successfully authenticated as " <> user.email <> ".")
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, _} ->
        conn
        |> put_flash(:error, "Invalid email or password")
        |> render("new.html")
    end
  end

  def login(conn, %{"user" => %{"email" => email, "password" => password}}) do
    Accounts.authenticate_user(email, password)
    |> login_reply(conn)
  end

  def logout(conn, _) do
    conn
    |> put_flash(:info, "You've been successfully logged out")
    |> Guardian.Plug.sign_out()
    |> redirect(to: Routes.page_path(conn, :index))
  end

  defp login_reply({:ok, user}, conn) do
    conn
    |> put_flash(:info, "Welcome back! " <> user.email)
    |> Guardian.Plug.sign_in(user)
    |> redirect(to: "/protected")
  end

  defp login_reply({:error, reason}, conn) do
    conn
    |> put_flash(:error, to_string(reason))
    |> new(%{})
  end

  def delete(conn, _) do
    conn
    |> Accounts.logout()
    |> put_flash(:info, "You've been successfully logged out")
    |> redirect(to: Routes.page_path(conn, :index))
  end
end

lib/biddy_web/views/session_view.ex
defmodule BiddyWeb.SessionView do
  use BiddyWeb, :view
end

lib/biddy_web/templates/session/new.html.eex
<div class="ui raised very padded text container segment">
  <h2 class="ui pink image header">
    <img src="<%= Routes.static_path(@conn, "/images/letter-b.png") %>" class="image">
    <div class="content">
      Log-in to your account
    </div>
  </h2>
  <%= form_for @conn, Routes.session_path(@conn, :create), [as: :user, class: "ui large form"], fn f-> %>
  <div class="ui stacked segment">
    <div class="field">
      <%= label f, :email, class: "control-label" %>
      <div class="ui left icon input">
        <i class="mail icon"></i>
        <%= email_input f, :email, placeholder: "Email address", autofocus: "true" %>
      </div>
      <%= error_tag f, :email %>
    </div>
    <div class="field">
      <%= label f, :password, class: "control-label" %>
      <div class="ui left icon input">
        <i class="lock icon"></i>
        <%= password_input f, :password, autocomplete: "false", placeholder: "Minimum 6 characters" %>
      </div>
      <%= error_tag f, :password %>
    </div>
    <div class="text-center">
      <%= submit "Log In", class: "ui pink fluid button" %>
    </div>
  </div>
<% end %>
<div class="ui message">
  <span class="spacer-mr">New to us?</span> <%= link raw(~s'<i class="user outline icon"></i>Sign up'), to: Routes.user_path(@conn, :new), class: "ui pink tiny button" %>
</div>
</div>